import { AccountStatus, Gender, RoleInAccount } from '@common/enums/account-role.enum'
export const accountStatuses = [
  // Admin account
  {
    name: 'Nguyễn Văn Nguyên',
    phone: '0123456789',
    address: 'Văn phòng quản trị, Thành phố Hồ Chí Minh',
    dateOfBirth: '1990-01-01',
    gender: Gender.Male,
    email: 'admin@naviora.com',
    password: 'Admin@123',
    role: RoleInAccount.Admin,
    status: AccountStatus.Active
  },
  {
    // Student account
    name: 'Nguyễn Thị Mai',
    phone: '0958574507',
    address: '22 đường Nguyễn Gia Trí, phường 7, quận Bình Thạnh, Thành phố Hồ Chí Minh',
    dateOfBirth: '2003-03-28',
    gender: Gender.Female,
    email: 'student1@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Trần Văn Đức',
    phone: '0912345678',
    address: '123 đường Lê Văn Việt, phường 9, quận Thủ Đức, Thành phố Hồ Chí Minh',
    dateOfBirth: '2002-05-15',
    gender: Gender.Male,
    email: 'student2@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Lê Thị Hương',
    phone: '0923456789',
    address: '456 đường Võ Văn Tần, phường 6, quận 3, Thành phố Hồ Chí Minh',
    dateOfBirth: '2004-08-22',
    gender: Gender.Female,
    email: 'student3@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Phạm Văn Hùng',
    phone: '0934567890',
    address: '789 đường Nguyễn Trãi, phường 5, quận 5, Thành phố Hồ Chí Minh',
    dateOfBirth: '2003-11-10',
    gender: Gender.Male,
    email: 'student4@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Hoàng Thị Linh',
    phone: '0945678901',
    address: '321 đường Lý Tự Trọng, phường 1, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '2002-02-18',
    gender: Gender.Female,
    email: 'student5@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Vũ Văn Nam',
    phone: '0956789012',
    address: '654 đường Pasteur, phường 6, quận 3, Thành phố Hồ Chí Minh',
    dateOfBirth: '2004-07-05',
    gender: Gender.Male,
    email: 'student6@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Đặng Thị Oanh',
    phone: '0967890123',
    address: '987 đường Cách Mạng Tháng Tám, phường 7, quận 10, Thành phố Hồ Chí Minh',
    dateOfBirth: '2003-09-30',
    gender: Gender.Female,
    email: 'student7@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Bùi Văn Phúc',
    phone: '0978901234',
    address: '147 đường Nguyễn Đình Chiểu, phường 6, quận 3, Thành phố Hồ Chí Minh',
    dateOfBirth: '2002-12-14',
    gender: Gender.Male,
    email: 'student8@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Ngô Thị Quỳnh',
    phone: '0989012345',
    address: '258 đường Hoàng Văn Thụ, phường 4, quận Tân Bình, Thành phố Hồ Chí Minh',
    dateOfBirth: '2004-04-25',
    gender: Gender.Female,
    email: 'student9@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Dương Văn Sơn',
    phone: '0990123456',
    address: '369 đường Nguyễn Văn Cừ, phường 4, quận 5, Thành phố Hồ Chí Minh',
    dateOfBirth: '2003-06-08',
    gender: Gender.Male,
    email: 'student10@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  // User account
  {
    name: 'Lý Thị Thanh',
    phone: '0911222333',
    address: '101 đường Trần Hưng Đạo, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '1995-07-12',
    gender: Gender.Female,
    email: 'user@example.com',
    password: 'User@123',
    role: RoleInAccount.User,
    status: AccountStatus.Active
  },
  // Lecturer account
  {
    name: 'Nguyễn Văn Sinh',
    phone: '0933445566',
    address: '45 đường Điện Biên Phủ, quận 3, Thành phố Hồ Chí Minh',
    dateOfBirth: '1985-11-05',
    gender: Gender.Male,
    email: 'lecturer@example.com',
    password: 'Lecturer@123',
    role: RoleInAccount.Lecturer,
    status: AccountStatus.Active
  },
  // Principal account
  {
    name: 'Trần Thị Thu Thảo',
    phone: '0988777666',
    address: '78 đường Lê Lợi, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '1970-04-18',
    gender: Gender.Female,
    email: 'principal@example.com',
    password: 'Principal@123',
    role: RoleInAccount.Principal,
    status: AccountStatus.Active
  },
  {
    name: 'Lê Văn Đức',
    phone: '0988777667',
    address: '89 đường Nguyễn Huệ, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '1972-08-22',
    gender: Gender.Male,
    email: 'principal2@example.com',
    password: 'Principal@123',
    role: RoleInAccount.Principal,
    status: AccountStatus.Active
  },
  {
    name: 'Phạm Thị Thu Hương',
    phone: '0988777668',
    address: '112 đường Đồng Khởi, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '1975-03-15',
    gender: Gender.Female,
    email: 'principal3@example.com',
    password: 'Principal@123',
    role: RoleInAccount.Principal,
    status: AccountStatus.Active
  },
  {
    name: 'Hoàng Văn Đạt',
    phone: '0988777669',
    address: '234 đường Lê Thánh Tôn, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '1973-11-30',
    gender: Gender.Male,
    email: 'principal4@example.com',
    password: 'Principal@123',
    role: RoleInAccount.Principal,
    status: AccountStatus.Unactive
  },
  // Additional Lecturer accounts (Biology lecturers)
  {
    name: 'Trần Thị Thu Hồng',
    phone: '0933445567',
    address: '56 đường Võ Thị Sáu, quận 3, Thành phố Hồ Chí Minh',
    dateOfBirth: '1986-02-14',
    gender: Gender.Female,
    email: 'lecturer2@example.com',
    password: 'Lecturer@123',
    role: RoleInAccount.Lecturer,
    status: AccountStatus.Active
  },
  {
    name: 'Lê Văn Đức',
    phone: '0933445568',
    address: '67 đường Trần Hưng Đạo, quận 5, Thành phố Hồ Chí Minh',
    dateOfBirth: '1987-06-20',
    gender: Gender.Male,
    email: 'lecturer3@example.com',
    password: 'Lecturer@123',
    role: RoleInAccount.Lecturer,
    status: AccountStatus.Active
  },
  {
    name: 'Phạm Thị Thu Thủy',
    phone: '0933445569',
    address: '78 đường Nguyễn Thị Minh Khai, quận 3, Thành phố Hồ Chí Minh',
    dateOfBirth: '1984-09-10',
    gender: Gender.Female,
    email: 'lecturer4@example.com',
    password: 'Lecturer@123',
    role: RoleInAccount.Lecturer,
    status: AccountStatus.Active
  },
  {
    name: 'Hoàng Văn Đạt',
    phone: '0933445570',
    address: '89 đường Lý Tự Trọng, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '1988-12-05',
    gender: Gender.Male,
    email: 'lecturer5@example.com',
    password: 'Lecturer@123',
    role: RoleInAccount.Lecturer,
    status: AccountStatus.Active
  },
  {
    name: 'Vũ Thị Thu Thủy',
    phone: '0933445571',
    address: '90 đường Pasteur, quận 3, Thành phố Hồ Chí Minh',
    dateOfBirth: '1985-04-18',
    gender: Gender.Female,
    email: 'lecturer6@example.com',
    password: 'Lecturer@123',
    role: RoleInAccount.Lecturer,
    status: AccountStatus.Active
  },
  {
    name: 'Thầy Đặng Văn Tiến Hóa',
    phone: '0933445572',
    address: '101 đường Nguyễn Du, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '1983-07-25',
    gender: Gender.Male,
    email: 'lecturer7@example.com',
    password: 'Lecturer@123',
    role: RoleInAccount.Lecturer,
    status: AccountStatus.Active
  },
  {
    name: 'Bùi Thị Thu',
    phone: '0933445573',
    address: '112 đường Hàm Nghi, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '1989-01-12',
    gender: Gender.Female,
    email: 'lecturer8@example.com',
    password: 'Lecturer@123',
    role: RoleInAccount.Lecturer,
    status: AccountStatus.Active
  },
  {
    name: 'Ngô Văn Đức',
    phone: '0933445574',
    address: '123 đường Lê Lợi, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '1982-10-08',
    gender: Gender.Male,
    email: 'lecturer9@example.com',
    password: 'Lecturer@123',
    role: RoleInAccount.Lecturer,
    status: AccountStatus.Active
  },
  {
    name: 'Dương Thị Thu Thủy',
    phone: '0933445575',
    address: '134 đường Nguyễn Huệ, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '1986-05-22',
    gender: Gender.Female,
    email: 'lecturer10@example.com',
    password: 'Lecturer@123',
    role: RoleInAccount.Lecturer,
    status: AccountStatus.Active
  },
  {
    name: 'Lưu Văn Động',
    phone: '0933445576',
    address: '145 đường Đồng Khởi, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '1984-08-30',
    gender: Gender.Male,
    email: 'lecturer11@example.com',
    password: 'Lecturer@123',
    role: RoleInAccount.Lecturer,
    status: AccountStatus.Active
  },
  {
    name: 'Mai Thị Thu Thủy',
    phone: '0933445577',
    address: '156 đường Lê Thánh Tôn, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '1987-03-15',
    gender: Gender.Female,
    email: 'lecturer12@example.com',
    password: 'Lecturer@123',
    role: RoleInAccount.Lecturer,
    status: AccountStatus.Unactive
  },
  // Additional Student accounts (Excellent Biology students)
  {
    name: 'Nguyễn Văn An',
    phone: '0901111111',
    address: '111 đường Trần Phú, phường 8, quận 5, Thành phố Hồ Chí Minh',
    dateOfBirth: '2003-01-15',
    gender: Gender.Male,
    email: 'student11@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Trần Thị Bình',
    phone: '0901111112',
    address: '222 đường Lê Hồng Phong, phường 4, quận 5, Thành phố Hồ Chí Minh',
    dateOfBirth: '2004-02-20',
    gender: Gender.Female,
    email: 'student12@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Lê Văn Cường',
    phone: '0901111113',
    address: '333 đường Nguyễn Văn Cừ, phường 6, quận 5, Thành phố Hồ Chí Minh',
    dateOfBirth: '2002-03-25',
    gender: Gender.Male,
    email: 'student13@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Phạm Thị Dung',
    phone: '0901111114',
    address: '444 đường An Dương Vương, phường 9, quận 5, Thành phố Hồ Chí Minh',
    dateOfBirth: '2005-04-10',
    gender: Gender.Female,
    email: 'student14@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Hoàng Văn Em',
    phone: '0901111115',
    address: '555 đường Hùng Vương, phường 10, quận 5, Thành phố Hồ Chí Minh',
    dateOfBirth: '2003-05-18',
    gender: Gender.Male,
    email: 'student15@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Vũ Thị Phương',
    phone: '0901111116',
    address: '666 đường Bà Triệu, phường 1, quận 10, Thành phố Hồ Chí Minh',
    dateOfBirth: '2004-06-22',
    gender: Gender.Female,
    email: 'student16@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Đặng Văn Giang',
    phone: '0901111117',
    address: '777 đường Lý Thường Kiệt, phường 2, quận 10, Thành phố Hồ Chí Minh',
    dateOfBirth: '2002-07-08',
    gender: Gender.Male,
    email: 'student17@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Bùi Thị Hoa',
    phone: '0901111118',
    address: '888 đường 3 Tháng 2, phường 3, quận 10, Thành phố Hồ Chí Minh',
    dateOfBirth: '2005-08-14',
    gender: Gender.Female,
    email: 'student18@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Đỗ Văn Hùng',
    phone: '0901111119',
    address: '999 đường Nguyễn Oanh, phường 4, quận Gò Vấp, Thành phố Hồ Chí Minh',
    dateOfBirth: '2003-09-30',
    gender: Gender.Male,
    email: 'student19@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Ngô Thị Lan',
    phone: '0901111120',
    address: '1000 đường Quang Trung, phường 5, quận Gò Vấp, Thành phố Hồ Chí Minh',
    dateOfBirth: '2004-10-05',
    gender: Gender.Female,
    email: 'student20@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Dương Văn Minh',
    phone: '0901111121',
    address: '1111 đường Phan Văn Trị, phường 6, quận Bình Thạnh, Thành phố Hồ Chí Minh',
    dateOfBirth: '2002-11-12',
    gender: Gender.Male,
    email: 'student21@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Trương Thị Nga',
    phone: '0901111122',
    address: '1222 đường Điện Biên Phủ, phường 7, quận Bình Thạnh, Thành phố Hồ Chí Minh',
    dateOfBirth: '2005-12-18',
    gender: Gender.Female,
    email: 'student22@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Lý Văn Oanh',
    phone: '0901111123',
    address: '1333 đường Xô Viết Nghệ Tĩnh, phường 8, quận Bình Thạnh, Thành phố Hồ Chí Minh',
    dateOfBirth: '2003-01-25',
    gender: Gender.Male,
    email: 'student23@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Phan Thị Phương',
    phone: '0901111124',
    address: '1444 đường Úng Văn Khiêm, phường 9, quận Bình Thạnh, Thành phố Hồ Chí Minh',
    dateOfBirth: '2004-02-28',
    gender: Gender.Female,
    email: 'student24@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Võ Văn Quang',
    phone: '0901111125',
    address: '1555 đường Bạch Đằng, phường 10, quận Bình Thạnh, Thành phố Hồ Chí Minh',
    dateOfBirth: '2002-03-15',
    gender: Gender.Male,
    email: 'student25@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Cao Thị Quỳnh',
    phone: '0901111126',
    address: '1666 đường Nguyễn Văn Đậu, phường 1, quận Bình Thạnh, Thành phố Hồ Chí Minh',
    dateOfBirth: '2005-04-20',
    gender: Gender.Female,
    email: 'student26@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Lưu Văn Sơn',
    phone: '0901111127',
    address: '1777 đường Đinh Tiên Hoàng, phường 2, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '2003-05-10',
    gender: Gender.Male,
    email: 'student27@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Mai Thị Thảo',
    phone: '0901111128',
    address: '1888 đường Mạc Đĩnh Chi, phường 3, quận 1, Thành phố Hồ Chí Minh',
    dateOfBirth: '2004-06-25',
    gender: Gender.Female,
    email: 'student28@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Hà Văn Thắng',
    phone: '0901111129',
    address: '1999 đường Nguyễn Đình Chiểu, phường 4, quận 3, Thành phố Hồ Chí Minh',
    dateOfBirth: '2002-07-08',
    gender: Gender.Male,
    email: 'student29@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Kiều Thị Uyên',
    phone: '0901111130',
    address: '2000 đường Võ Văn Tần, phường 5, quận 3, Thành phố Hồ Chí Minh',
    dateOfBirth: '2005-08-12',
    gender: Gender.Female,
    email: 'student30@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Nguyễn Văn Vinh',
    phone: '0901111131',
    address: '2111 đường Pasteur, phường 6, quận 3, Thành phố Hồ Chí Minh',
    dateOfBirth: '2003-09-18',
    gender: Gender.Male,
    email: 'student31@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Trần Thị Xuân',
    phone: '0901111132',
    address: '2222 đường Hai Bà Trưng, phường 7, quận 3, Thành phố Hồ Chí Minh',
    dateOfBirth: '2004-10-22',
    gender: Gender.Female,
    email: 'student32@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Lê Văn Yên',
    phone: '0901111133',
    address: '2333 đường Nguyễn Thị Minh Khai, phường 8, quận 3, Thành phố Hồ Chí Minh',
    dateOfBirth: '2002-11-30',
    gender: Gender.Male,
    email: 'student33@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Phạm Thị Anh',
    phone: '0901111134',
    address: '2444 đường Điện Biên Phủ, phường 9, quận 3, Thành phố Hồ Chí Minh',
    dateOfBirth: '2005-12-05',
    gender: Gender.Female,
    email: 'student34@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Active
  },
  {
    name: 'Hoàng Văn Bảo',
    phone: '0901111135',
    address: '2555 đường Cách Mạng Tháng Tám, phường 10, quận 10, Thành phố Hồ Chí Minh',
    dateOfBirth: '2003-01-15',
    gender: Gender.Male,
    email: 'student35@example.com',
    role: RoleInAccount.Student,
    password: 'Student@123',
    status: AccountStatus.Unactive
  }
]
